//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eqwh.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACDR
    {
        public Nullable<int> Hadith1 { get; set; }
        public Nullable<byte> Ahadith_Book { get; set; }
        public string Ahadith_ACDNo { get; set; }
        public Nullable<int> Hadith2 { get; set; }
        public Nullable<byte> Ahadith_1_Book { get; set; }
        public string Ahadith_1_ACDNo { get; set; }
        public bool Review { get; set; }
        public Nullable<int> NewHadith1 { get; set; }
        public Nullable<int> NewHadith2 { get; set; }
    }
}
