//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eqwh.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ahadith
    {
        public int Id { get; set; }
        public Nullable<int> ReferenceEvent { get; set; }
        public byte Book { get; set; }
        public byte Part { get; set; }
        public short PartHNo { get; set; }
        public int Topic { get; set; }
        public string Chapter { get; set; }
        public string UrduText { get; set; }
        public string EnglishText { get; set; }
        public string ArabicText { get; set; }
        public string ArabicWithoutAraabText { get; set; }
        public string Takhreej { get; set; }
        public string Ravi { get; set; }
        public string ACDNo { get; set; }
        public Nullable<int> HadithRepetitionCounter { get; set; }
        public string MutafiqAlaih { get; set; }
        public Nullable<int> MutafiqAlaihCounter { get; set; }
        public Nullable<int> TashreehReference { get; set; }
        public Nullable<int> ACD { get; set; }
        public string UrduTextColor { get; set; }
        public string ArabicTextColor { get; set; }
        public string EnglishTextColor { get; set; }
        public string BaabUrdu_DS { get; set; }
        public string HukamAjmali_DS { get; set; }
        public string Qisam_DS { get; set; }
        public string Nisbat_DS { get; set; }
        public string HNo_DS { get; set; }
        public string ArabicText_DS { get; set; }
        public string UrduText_DS { get; set; }
    }
}
