//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eqwh.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AhadithLayoutDetail
    {
        public int Id { get; set; }
        public int Layout { get; set; }
        public string Column { get; set; }
        public string Font { get; set; }
        public int FontSize { get; set; }
        public string ForeColor { get; set; }
        public string BackColor { get; set; }
        public string ReadOnly { get; set; }
    }
}
