//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eqwh.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ravi
    {
        public Nullable<int> ID { get; set; }
        public int Tabqa { get; set; }
        public string Ravi1 { get; set; }
        public string Kuniat { get; set; }
        public string Nasab { get; set; }
        public string Laqab { get; set; }
    }
}
