//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eqwh.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaviAhadithACD
    {
        public int Ravi { get; set; }
        public string RaviName { get; set; }
        public int ACD { get; set; }
        public byte Book { get; set; }
    }
}
