//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eqwh.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagType
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Font { get; set; }
        public string Color { get; set; }
        public bool Hyperlink { get; set; }
    }
}
