//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eqwh.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicsAhadithACD
    {
        public Nullable<int> ACD { get; set; }
        public int Topic { get; set; }
        public Nullable<byte> Book { get; set; }
        public string Ravi { get; set; }
    }
}
